### ISSUE TITLE
Reactjs

### ISSUE THREAD

**Issue by vitrinh282** [Drarig29/brackets-viewer.js#73] opened 2021-09-28 13:43 UTC
how can use it in reactjs ?

**Comment by Drarig29** [comment] 2021-09-28 13:54
For now, the preferred way is like this: https://replit.com/@Drarig29/React-and-brackets-viewerjs

**Comment by Drarig29** [comment] 2021-09-28 13:57
Duplicate of #20

**Closed** 2021-09-28 13:57 UTC
