### ISSUE TITLE
Issues with connecting lines on Single Eliminations with odd number of teams

### ISSUE THREAD

**Issue by poppabear8883** [Drarig29/brackets-viewer.js#101] opened 2024-01-03 01:56 UTC
![image](https://github.com/Drarig29/brackets-viewer.js/assets/7263458/4f64fc9e-e0cd-415b-9c14-33f1852b31e0)

**Comment by Drarig29** [comment] 2024-01-03 04:51
Hi! Would you be able to send the JSON for both the screenshots?

**Comment by Drarig29** [comment] 2024-01-03 04:54
Am I right saying both screenshots are for the same data, but just rendered in different contexts?

It looks like you bot's screenshot generation may introduce a bug with CSS or something like that

**Comment by poppabear8883** [comment] 2024-01-03 06:18
The bots screenshot literally uses your library to render the bracket. The
image the bot posts in discord is literally a screenshot of the rendered
html via a url.


The other image in white is directly from Tournament.com

**Comment by poppabear8883** [comment] 2024-01-03 06:19
I can provide more details tomorrow, I'm away from my desk for the night

**Comment by poppabear8883** [comment] 2024-01-07 18:25
Sorry just now getting back to this issue.

So basically the dark screenshot is from your rendered html and the white version is the Toornament.com rendered bracket.

`Web Page`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bracket</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/brackets-viewer/dist/brackets-viewer.min.css"/>
    <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/brackets-viewer/dist/brackets-viewer.min.js"></script>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
<div class="logo">
    <img src="images/logo.png" alt="Logo"/>
</div>

<div class="brackets-viewer"></div>

<script>
    function getQueryParam(name) {
        const urlParams = new URLSearchParams(window.location.search);
        return urlParams.get(name);
    }

    async function fetchDataAndRender() {
        const tournamentId = getQueryParam("tournamentId");
        if (!tournamentId) {
            alert("tournamentId not provided in the URL");
            return;
        }

        try {
            const origin = window.location.origin;
            const response = await fetch(`${origin}/api/bracket?tournamentId=${tournamentId}`);

            if (!response.ok) {
                throw new Error("Network response was not ok");
            }
            const data = await response.json();

            if (!data.stage.length) {
                alert('There is no stage for this tournament. Most likely because the tournament has not started!');
            }

            await window.bracketsViewer.render({
                stages: data.stage,
                matches: data.match,
                matchGames: data.match_game,
                participants: data.participant,
            });

            console.log('Render finished');
        } catch (error) {
            console.error("There was a problem with the fetch operation:", error.message);
        }
    }

    fetchDataAndRender();
</script>
</body>
</html>
```

`API Route`
```js
const express = require('express');
const {convertData} = require("brackets-toornament-layer");
const router = express.Router();

router.get('/', express.raw({type: 'application/json'}), async (req, res) => {
    const client = req.discordClient;
    const tournamentId = req.query.tournamentId;

    const stages = await client.toor.getStages(tournamentId);
    const matches = await client.toor.getMatches(tournamentId);

    const data = convertData({
        tournament_id: tournamentId,
        stages: stages,
        matches: matches
    }).database;

    res.json(data);
});

module.exports = router;
```

`How the bot screenshots the bracket to post it on Discord`
```js
client.fetchBracket = async (tournamentId) => {
        const browser = await puppeteer.launch({headless: "new"});
        const page = await browser.newPage();
        
        await page.goto(
            `${EXPRESS_URL}/bracket.html?tournamentId=${tournamentId}`,
            {waitUntil: 'networkidle0'}
        );
        
        await page.setViewport({width: 1280, height: 800});

        try {
            await page.waitForSelector('.brackets-viewer');
        } catch (e) {
            console.log(chalk.red('The bracket element was not found on the page.'));
            await browser.close();
            return null;
        }
        
        const bracketElement = await page.$('.brackets-viewer');
        if (bracketElement) {
            const imageBuffer = await bracketElement.screenshot();
            await browser.close();
            
            return new AttachmentBuilder(imageBuffer, {name: 'bracket.png'});
        } else {
            console.log(chalk.red('The bracket element was not found on the page.'));
            await browser.close();
            return null;
        }
    }
```

**Comment by poppabear8883** [comment] 2024-01-14 17:06
I'm noticing that this is not just with odd number of teams, ran with 12 teams Double Elimination last night and the connecting lines were also all jacked up.

![image](https://github.com/Drarig29/brackets-viewer.js/assets/7263458/07fecc52-0468-48f4-a9a6-a59e70bf09dd)

**Comment by Drarig29** [comment] 2024-01-21 15:40
Hi @poppabear8883! I cannot debug without JSON.

Can you send a minimal example where the connecting lines are broken, with the resulting data from:

```js
const stages = await client.toor.getStages(tournamentId);
const matches = await client.toor.getMatches(tournamentId);
```

Something like:

`stages`
```jsonc
{ 
  // JSON data coming from Toornament, before conversion
}
```

`matches`
```jsonc
{ 
  // JSON data coming from Toornament, before conversion
}
```

**Comment by Drarig29** [comment] 2024-01-21 15:42
I made a reproduction with JSON data generated by the manager directly, and your CSS doesn't seem to be the culprit, nor Puppeteer as I thought.

So it may be an issue with the `brackets-toornament-layer`, hence why I want your JSON data **before conversion**.

Thanks, and sorry for the delay.

**Comment by poppabear8883** [comment] 2024-01-21 16:37
`Resulting Render`
![image](https://github.com/Drarig29/brackets-viewer.js/assets/7263458/ac976d18-45de-40ce-b05e-8e0503cd8a66)


`JSON DATA`
```json
{
   "stage":[
      {
         "id":0,
         "tournament_id":0,
         "name":"Stage 1",
         "type":"single_elimination",
         "number":1,
         "settings":{
            "size":11,
            "consolationFinal":false
         }
      }
   ],
   "match":[
      {
         "id":0,
         "stage_id":0,
         "group_id":0,
         "round_id":0,
         "number":1,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":0,
            "result":"win"
         },
         "opponent2":{
            "id":1,
            "result":"loss"
         }
      },
      {
         "id":1,
         "stage_id":0,
         "group_id":0,
         "round_id":0,
         "number":2,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":2,
            "result":"win"
         },
         "opponent2":{
            "id":3,
            "result":"loss"
         }
      },
      {
         "id":2,
         "stage_id":0,
         "group_id":0,
         "round_id":0,
         "number":3,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":4,
            "result":"loss"
         },
         "opponent2":{
            "id":5,
            "result":"win"
         }
      },
      {
         "id":3,
         "stage_id":0,
         "group_id":0,
         "round_id":1,
         "number":1,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":6,
            "result":"loss"
         },
         "opponent2":{
            "id":0,
            "result":"win"
         }
      },
      {
         "id":4,
         "stage_id":0,
         "group_id":0,
         "round_id":1,
         "number":2,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":7,
            "result":"win"
         },
         "opponent2":{
            "id":8,
            "result":"loss"
         }
      },
      {
         "id":5,
         "stage_id":0,
         "group_id":0,
         "round_id":1,
         "number":3,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":9,
            "result":"loss"
         },
         "opponent2":{
            "id":2,
            "result":"win"
         }
      },
      {
         "id":6,
         "stage_id":0,
         "group_id":0,
         "round_id":1,
         "number":4,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":10,
            "result":"win"
         },
         "opponent2":{
            "id":5,
            "result":"loss"
         }
      },
      {
         "id":7,
         "stage_id":0,
         "group_id":0,
         "round_id":2,
         "number":1,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":0,
            "result":"loss"
         },
         "opponent2":{
            "id":7,
            "result":"win"
         }
      },
      {
         "id":8,
         "stage_id":0,
         "group_id":0,
         "round_id":2,
         "number":2,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":2,
            "result":"win"
         },
         "opponent2":{
            "id":10,
            "result":"loss"
         }
      },
      {
         "id":9,
         "stage_id":0,
         "group_id":0,
         "round_id":3,
         "number":1,
         "child_count":0,
         "status":4,
         "opponent1":{
            "id":7,
            "result":"loss"
         },
         "opponent2":{
            "id":2,
            "result":"win"
         }
      }
   ],
   "match_game":[
      
   ],
   "participant":[
      {
         "id":0,
         "name":"RawRrs",
         "tournament_id":0
      },
      {
         "id":1,
         "name":"Black Ops 3",
         "tournament_id":0
      },
      {
         "id":2,
         "name":"TheBoys",
         "tournament_id":0
      },
      {
         "id":3,
         "name":"NotPlanting",
         "tournament_id":0
      },
      {
         "id":4,
         "name":"My Dick",
         "tournament_id":0
      },
      {
         "id":5,
         "name":"Hope",
         "tournament_id":0
      },
      {
         "id":6,
         "name":"Panera Bread",
         "tournament_id":0
      },
      {
         "id":7,
         "name":"FalseGods",
         "tournament_id":0
      },
      {
         "id":8,
         "name":"ShowerCapZ",
         "tournament_id":0
      },
      {
         "id":9,
         "name":"BU COD ACAD",
         "tournament_id":0
      },
      {
         "id":10,
         "name":"Beeky&YoungPups",
         "tournament_id":0
      }
   ]
}
```

**Comment by Drarig29** [comment] 2024-01-21 16:50
@poppabear8883 thanks for editing your answer. However, you have some `opponents: [ [Object], [Object] ]`.

Can you `JSON.stringify()` your data? I don't care if everything is minified on one line, I will format it on my side.

**Comment by Drarig29** [comment] 2024-01-21 16:53
The viewer library **only supports displaying even numbers of matches**, so as part of https://github.com/Drarig29/brackets-viewer.js/issues/50, I introduced hidden matches, which keep the "pyramidal" structure, so that the connecting lines aren't messed up.

I think there should be a way to change the `brackets-toornament-layer` a bit so that it understands where to introduce hidden matches.

**Comment by poppabear8883** [comment] 2024-01-21 16:53
> @poppabear8883 thanks for editing your answer. However, you have some `opponents: [ [Object], [Object] ]`.
> 
> Can you `JSON.stringify()` your data? I don't care if everything is minified on one line, I will format it on my side.

Sorry I was actually working on it. Its been updated.

**Comment by Drarig29** [comment] 2024-01-21 17:23
@poppabear8883 which endpoint of the Toornament API is `client.toor.getMatches()` using?

**Comment by poppabear8883** [comment] 2024-01-21 17:28
> @poppabear8883 which endpoint of the Toornament API is `client.toor.getMatches()` using?

```js
const resp = await axios.get(`https://api.toornament.com/organizer/v2/matches`, {
                params: {
                    tournament_ids: tournamentId,
                    ...params
                },
                headers: {
                    Range: `matches=0-99`
                }
            });

            return resp.data || resp;
```

**Comment by Drarig29** [comment] 2024-01-21 17:35
@poppabear8883 can you use [`https://api.toornament.com/organizer/v2/bracket-nodes`](https://developer.toornament.com/v2/doc/organizer_bracket_nodes) instead?

It returns the `source_node_id` property:

![image](https://github.com/Drarig29/brackets-viewer.js/assets/9317502/fed97cec-3b42-4661-9224-c78d123151d0)

And this property points to the previous match where an opponent comes from, this is really important for me to fix the bug you are having.

By the way, this is documented in the `brackets-toornament-layer`'s README: https://github.com/Drarig29/brackets-toornament-layer#input

**Comment by Drarig29** [comment] 2024-01-21 17:58
Once you manage to use this endpoint, can you send me the resulting JSON as well? Thanks!

**Comment by poppabear8883** [comment] 2024-01-21 20:26
```json
[
   {
      "id":"7331835958950002721",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002742",
      "number":1,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T00:49:08+00:00",
      "depth":4,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331630799700746240",
               "name":"RawRrs",
               "custom_user_identifier":"736392184181293090",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         },
         {
            "number":2,
            "participant":{
               "id":"7331689482516234240",
               "name":"Black Ops 3",
               "custom_user_identifier":"715267250176917665",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         }
      ]
   },
   {
      "id":"7331835958950002733",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002742",
      "number":2,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T00:21:44+00:00",
      "depth":4,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331547042633170944",
               "name":"TheBoys",
               "custom_user_identifier":"389524283350581248",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         },
         {
            "number":2,
            "participant":{
               "id":"7331730157094264832",
               "name":"NotPlanting",
               "custom_user_identifier":"574163119472115712",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         }
      ]
   },
   {
      "id":"7331835958950002739",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002742",
      "number":3,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T00:58:52+00:00",
      "depth":4,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331501202386173952",
               "name":"My Dick",
               "custom_user_identifier":"754436966606569622",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         },
         {
            "number":2,
            "participant":{
               "id":"7331833466960707584",
               "name":"Hope",
               "custom_user_identifier":"750631555805872128",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         }
      ]
   },
   {
      "id":"7331835958950002718",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002743",
      "number":1,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T01:56:30+00:00",
      "depth":3,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331033600537804800",
               "name":"Panera Bread",
               "custom_user_identifier":"354147597272875009",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         },
         {
            "number":2,
            "participant":{
               "id":"7331630799700746240",
               "name":"RawRrs",
               "custom_user_identifier":"736392184181293090",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002721"
         }
      ]
   },
   {
      "id":"7331835958950002724",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002743",
      "number":2,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T00:38:31+00:00",
      "depth":3,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331385880433041408",
               "name":"FalseGods",
               "custom_user_identifier":"818889103092744233",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         },
         {
            "number":2,
            "participant":{
               "id":"7331473421928513536",
               "name":"ShowerCapZ",
               "custom_user_identifier":"817971012322590751",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         }
      ]
   },
   {
      "id":"7331835958950002730",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002743",
      "number":3,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T00:54:41+00:00",
      "depth":3,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331076719121473536",
               "name":"BU COD ACAD",
               "custom_user_identifier":"620079911247282225",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         },
         {
            "number":2,
            "participant":{
               "id":"7331547042633170944",
               "name":"TheBoys",
               "custom_user_identifier":"389524283350581248",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002733"
         }
      ]
   },
   {
      "id":"7331835958950002736",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002743",
      "number":4,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T01:43:10+00:00",
      "depth":3,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331192746552819712",
               "name":"Beeky&YoungPups",
               "custom_user_identifier":"705614129871716372",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"none",
            "source_node_id":null
         },
         {
            "number":2,
            "participant":{
               "id":"7331833466960707584",
               "name":"Hope",
               "custom_user_identifier":"750631555805872128",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002739"
         }
      ]
   },
   {
      "id":"7331835958950002715",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002744",
      "number":1,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T02:43:35+00:00",
      "depth":2,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331630799700746240",
               "name":"RawRrs",
               "custom_user_identifier":"736392184181293090",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002718"
         },
         {
            "number":2,
            "participant":{
               "id":"7331385880433041408",
               "name":"FalseGods",
               "custom_user_identifier":"818889103092744233",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002724"
         }
      ]
   },
   {
      "id":"7331835958950002727",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002744",
      "number":2,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T02:33:19+00:00",
      "depth":2,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331547042633170944",
               "name":"TheBoys",
               "custom_user_identifier":"389524283350581248",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002730"
         },
         {
            "number":2,
            "participant":{
               "id":"7331192746552819712",
               "name":"Beeky&YoungPups",
               "custom_user_identifier":"705614129871716372",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002736"
         }
      ]
   },
   {
      "id":"7331835958916448280",
      "tournament_id":"7320507024253435904",
      "stage_id":"7331835957674934272",
      "group_id":"7331835958916448279",
      "round_id":"7331835958950002745",
      "number":1,
      "type":"duel",
      "status":"completed",
      "scheduled_datetime":null,
      "played_at":"2023-12-05T03:43:16+00:00",
      "depth":1,
      "branch":"wb",
      "opponents":[
         {
            "number":1,
            "participant":{
               "id":"7331385880433041408",
               "name":"FalseGods",
               "custom_user_identifier":"818889103092744233",
               "custom_fields":{
                  
               }
            },
            "position":2,
            "rank":null,
            "result":"loss",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002715"
         },
         {
            "number":2,
            "participant":{
               "id":"7331547042633170944",
               "name":"TheBoys",
               "custom_user_identifier":"389524283350581248",
               "custom_fields":{
                  
               }
            },
            "position":1,
            "rank":null,
            "result":"win",
            "forfeit":false,
            "score":null,
            "source_type":"winner",
            "source_node_id":"7331835958950002727"
         }
      ]
   }
]
```

![image](https://github.com/Drarig29/brackets-viewer.js/assets/7263458/c31e7ced-f69e-400a-b0ee-c13f149deb59)


This looks much better, maybe that was the whole issue ? I simply over looked that bit of documentation.

**Comment by Drarig29** [comment] 2024-01-23 19:45
Oh lol, I had overlooked the end of your last message, with the screenshot. Indeed, it works perfectly this way and I have nothing to change, nice!

I confirm this is looks exactly how I expect, so I'll close the issue 👌 

Thank you for your patience!

**Closed by Drarig29** 2024-01-23 19:45 UTC
